## Logistic Regression

Logistic regression is a supervised machine learning algoritim used for binary classification. The model minimizes the log loss/binary crossentropy function, and the model outputs probabilties.

minimize => (-1/N) x sum(yi*ln(y_hat) + (1-yi)*ln(1-yhat))

In [91]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
import pandas as pd

In [92]:
X, y = make_classification(1000, n_features=10)
X = np.concatenate([X, np.ones((X.shape[0],1))], axis=1)

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print("X train shape: ",x_train.shape)
print("X test shape: ",x_test.shape)

print("y shape: ",y_train.shape)


X train shape:  (700, 11)
X test shape:  (300, 11)
y shape:  (700,)


In [93]:
x_train[0:5, :]

array([[-0.36899454, -0.81128008,  0.5546953 , -0.88728136,  0.64324758,
         1.58393914,  2.54515858, -1.08957926, -0.78444996,  2.01486467,
         1.        ],
       [ 0.45784994, -1.81202345, -0.29671724,  1.4820265 ,  0.18419947,
         0.54563641,  0.12173372, -0.83543247,  0.5344979 ,  0.68613971,
         1.        ],
       [-0.4154007 , -0.34100446, -0.25620236,  0.29484515,  0.45748059,
         0.39927878,  2.55670604, -0.9638873 , -0.88340547,  1.92564922,
         1.        ],
       [ 0.37117763,  0.4224644 , -0.7235174 , -1.45627326, -0.75876592,
        -0.6586552 , -2.59821578,  0.72852947,  1.08104593, -1.76792711,
         1.        ],
       [-0.26224421,  1.74789502,  0.95799429,  0.5707671 ,  1.87845541,
         0.33087489, -1.16632875, -0.10082156,  0.79771846, -0.47147796,
         1.        ]])

In [94]:
y_train[0:5]

array([1, 1, 1, 0, 1])

In [95]:
from math import e
class LogisticRegression:

  def __init__(self, lr, epochs=10, thresh=0.7):

    self.lr = lr
    self.epochs = epochs
    self.thresh = thresh
    self.w = None

  def sigmoid(self, x):

    return 1 / (1 + e**-x)

    # -1 * (1 + e**x)**-2 * -e**-x * X[i, :]


  def fit(self, X, y):

    self.w = np.random.randn(X.shape[1],)

    for epoch in range(self.epochs):

      gradient = np.full_like(self.w, 0)

      for i in range(X.shape[0]):

        y_p = self.sigmoid(y[i])

        y_hat_p = self.sigmoid(np.dot(self.w.T, X[i, :]))

        gradient += ((y_p / y_hat_p) * (-1 * (1 + e**-y_hat_p)**-2) * (-e**-y_hat_p) * X[i, :]) + (((1-y_p) / (1-y_hat_p)) * (-1 * (1 + e**-(1-y_hat_p))**-2) * (-e**-(1-y_hat_p)) * -X[i, :]) # gradient is wrong do it by hand

      gradient *= (-1/X.shape[0])

      self.w -= self.lr*gradient

  def predict(self, X):

    return X @ self.w

  def predict_proba(self, X):

    return self.sigmoid(self.predict(X))





In [96]:
log = LogisticRegression(0.1, 10, 0.7)
log.fit(x_train, y_train)
log.w

Streaming output truncated to the last 5000 lines.
-2130172351.5807278
-1381489815.850967
-438589844.5417373
-2155084592.5955496
3118730304.671317
-870148490.3021152
3266486794.7803745
1788453839.7423916
1633947946.6310265
3763051127.1306686
3198938419.739999
-1377252228.131343
-380858956.74361086
-790861566.7340848
-3063418641.0802183
-1201236831.2321908
863164740.7869278
2949561820.201004
-1920527693.792185
-2380102136.6751976
5211840926.200695
-346666869.7465352
2063049502.5215828
1566381238.2047703
-3481513222.371399
-2106382504.0979502
-2359706229.9521856
1942497888.6396036
-1057212852.056078
101515737.68734807
-680434957.8797154
4617447290.973962
29199300.537879348
-2591937788.4236727
-1753958936.7990131
3946237536.5692463
-2931763939.215474
3773170597.8403397
-3572301408.678296
445521881.7210734
331792732.6292008
3375131910.0899925
738821940.3667566
1983775749.7775254
-3404737282.410617
-3890806882.17027
3059196095.4767075
-1292509661.9996243
-486067492.88572335
-2034487641.4103

/tmp/ipython-input-88833392.py:13: RuntimeWarning: overflow encountered in scalar power
  return 1 / (1 + e**-x)
/tmp/ipython-input-88833392.py:32: RuntimeWarning: divide by zero encountered in scalar divide
  gradient += ((y_p / y_hat_p) * (-1 * (1 + e**-y_hat_p)**-2) * (-e**-y_hat_p) * X[i, :]) + (((1-y_p) / (1-y_hat_p)) * (-1 * (1 + e**-(1-y_hat_p))**-2) * (-e**-(1-y_hat_p)) * -X[i, :])
/tmp/ipython-input-88833392.py:32: RuntimeWarning: invalid value encountered in add
  gradient += ((y_p / y_hat_p) * (-1 * (1 + e**-y_hat_p)**-2) * (-e**-y_hat_p) * X[i, :]) + (((1-y_p) / (1-y_hat_p)) * (-1 * (1 + e**-(1-y_hat_p))**-2) * (-e**-(1-y_hat_p)) * -X[i, :])


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [98]:
pd.DataFrame({"Actual Label": y_test, "Predicted Prob": log.predict_proba(x_test)})

Actual Label  Predicted Prob
0               1             NaN
1               1             NaN
2               0             NaN
3               0             NaN
4               1             NaN
..            ...             ...
295             0             NaN
296             0             NaN
297             0             NaN
298             1             NaN
299             0             NaN

[300 rows x 2 columns]